### ISSUE TITLE
上传图片后没有返回任何信息

### ISSUE THREAD

**Issue by exusiai07** [ppxxxg22/nonebot_plugin_RealESRGAN#10]
![YUPLA3 _ST}`T_{W4OFG95F](https://github.com/Staskaer/nonebot_plugin_RealESRGAN/assets/112692808/514f54bb-e92d-4421-a0d4-5d8625944c8d)

**Comment by Staskaer** [comment]
这个....最近忙着升学的事，之前搭的服务器已经拆光了，所以现在本地没法测试，之前有人发了类似的issue当时注意到主要有两个原因

- 图片太大
- 更换API为`https://akhaliq-real-esrgan.hf.space/api/predict/`

**Comment by exusiai07** [comment]
> 这个....最近忙着升学的事，之前搭的服务器已经拆光了，所以现在本地没法测试，之前有人发了类似的issue当时注意到主要有两个原因
> 
> * 图片太大
> * 更换API为`https://akhaliq-real-esrgan.hf.space/api/predict/`

感谢，按第二个API修改以后收到了错误信息，在您列出的仓库里换了一个，能用了
