### ISSUE TITLE
nonebot版本2.0.0-rc1 运行报错

### ISSUE THREAD

**Issue by bhshuya** [ppxxxg22/nonebot_plugin_RealESRGAN#5]
大佬能否对该版本适配呢
![image](https://user-images.githubusercontent.com/77972386/196023391-69d94f21-464e-4e57-b356-b02c98b348df.png)

**Comment by Staskaer** [comment]
你更新一下此插件的版本试试呢，我前一段时间的提交的代码就移除了`State`等过时组件。我本地环境也一直是`nonebot 2.0.0-rc1`，使用是正常的。

**Comment by Staskaer** [comment]
我又确认了一下我确实是更新过的，即 #3 

包的最新版本应该是`2.1`

如果更新后还是不能运行的话麻烦贴一下运行环境，我再详细查查原因
