### ISSUE TITLE
request entity too large

### ISSUE THREAD

**Issue by Yuelioi** [ppxxxg22/nonebot_plugin_RealESRGAN#7]
200K的图片 居然显示过大

在原作官方文档也没见到如何自建API相关啊

**Comment by ppxxxg22** [comment]
1

**Comment by ppxxxg22** [comment]
1. 描述过于模糊，请问是多次尝试后仍然不可以吗

**Comment by Staskaer** [comment]
1. 描述有点模糊，请问是多次尝试后也不可以吗，能否截取下服务端的输出日志相关
2. 自建API可以看[这里](https://github.com/ppxxxg22/nonebot_plugin_RealESRGAN/commit/d968ca0db26ba1e9c6a99ddd9fda77136dee8cff?short_path=2370246#diff-2370246dfe54258882cd232a6f5ae115f2f277e370aafabcd52eebcb1b379b0e)，但是最好为您自建的API仓库取一个不常见的名字，以免污染搜索列表。(或者尝试hugface的clone方式，那个有点麻烦，我没细看)

**Comment by Yuelioi** [comment]
> 1. 描述有点模糊，请问是多次尝试后也不可以吗，能否截取下服务端的输出日志相关
> 2. 自建API可以看[这里](https://github.com/ppxxxg22/nonebot_plugin_RealESRGAN/commit/d968ca0db26ba1e9c6a99ddd9fda77136dee8cff?short_path=2370246#diff-2370246dfe54258882cd232a6f5ae115f2f277e370aafabcd52eebcb1b379b0e)，但是最好为您自建的API仓库取一个不常见的名字，以免污染搜索列表。(或者尝试hugface的clone方式，那个有点麻烦，我没细看)

对 多次尝试都不行 感觉是图片太大了, 同时间20k 60k的都行

~好滴 我研究下
