### ISSUE TITLE
接收到图片后没有返回

### ISSUE THREAD

**Issue by ElainaFanBoy** [ppxxxg22/nonebot_plugin_RealESRGAN#9]
环境py3.9.12、nb2rc4，自建仓库，插件使用最新版本，没有报错，网络可以正常访问抱脸

**Comment by Staskaer** [comment]
检查了一下，发现是huggingface的推断接口API地址变更导致的

比如，默认的地址**更改前是**：`https://hf.space/embed/ppxxxg22/Real-ESRGAN/api/predict/`，**更改后应该为**：`https://ppxxxg22-real-esrgan.hf.space/api/predict/`

如果是其他自己建的仓，API仿照第二个格式进行更改即可。

**Comment by ElainaFanBoy** [comment]
> 检查了一下，发现是huggingface的推断接口API地址变更导致的
> 
> 比如，默认的地址**更改前是**：`https://hf.space/embed/ppxxxg22/Real-ESRGAN/api/predict/`，**更改后应该为**：`https://ppxxxg22-real-esrgan.hf.space/api/predict/`
> 
> 如果是其他自己建的仓，API仿照第二个格式进行更改即可。

感谢，辛苦了

**Comment by ElainaFanBoy** [comment]
> 检查了一下，发现是huggingface的推断接口API地址变更导致的
> 
> 比如，默认的地址**更改前是**：`https://hf.space/embed/ppxxxg22/Real-ESRGAN/api/predict/`，**更改后应该为**：`https://ppxxxg22-real-esrgan.hf.space/api/predict/`
> 
> 如果是其他自己建的仓，API仿照第二个格式进行更改即可。

替换后可以了
